process.setUncaughtExceptionCaptureCallback((err) => {
  console.log(err);
});
